#!/bin/sh
module="shofer"
device="shofer"
mode="666"

/sbin/insmod ./$module.ko $* || exit 1

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

driver_num=$((driver_num-1))

rm -f /dev/${device}
mknod /dev/${device}
chmod $mode /dev/${device}
echo "Created device /dev/${device}"
